# Generated by Django 5.0.7 on 2024-08-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Documents For FMD',
            },
        ),
        migrations.CreateModel(
            name='FilesPredicts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.CharField(blank=True, max_length=150)),
                ('original_file_url', models.TextField(blank=True)),
                ('Prediction_file', models.CharField(blank=True, max_length=150)),
                ('Prediction_file_url', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Files Prediction',
            },
        ),
    ]
